name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install backend dependencies and run tests
      run: |
        cd backend
        npm install
        npm test

    - name: Install frontend dependencies and run tests
      run: |
        cd ../frontend
        npm install
        npm test

    - name: Auto-merge dev to main (on dev push)
      if: github.ref == 'refs/heads/dev'
      uses: devops-actions/merge-branch@v1.3.0
      with:
        from_branch: dev
        target_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Run E2E tests
      run: |
        npm install selenium-webdriver chromedriver
        node e2e-tests/test.js

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker-compose build
        docker-compose push
        
    - name: Install Docker Compose
      run: sudo apt-get install -y docker-compose